### ISSUE TITLE
Conveyer + JustifiedInfiniteGrid

### ISSUE THREAD

**Issue by Nickonimus** [naver/egjs-conveyer#36]
Hello, thank you for a great tools!

I trying to make conveyer work with JustifiedInfiniteGrid by this example:
https://naver.github.io/egjs-conveyer/docs/examples/InfiniteScroll
But can't make them work together.
So can you please explain how to use theme together, or provide example?

**Comment by malangfox** [comment]
Hello @Nickonimus.

The example in the demo link you left seems to be MasonryInfiniteGrid.
I'm not sure what you want between JustifiedInfiniteGrid and MasonryInfiniteGrid, but I've created demos for both.

- https://codepen.io/malangfox/pen/PoyrVNb Conveyer + MasonryInfiniteGrid
- https://codepen.io/malangfox/pen/zYmgYbZ Conveyer + JustifiedInfiniteGrid

I hope this can help you. Feel free to leave a comment if you have any questions.
